FROM pytorch/pytorch:2.7.0-cuda12.6-cudnn9-runtime

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    nano \
    ffmpeg \
    libturbojpeg0-dev \
    git \
    libgl1 

WORKDIR /app

COPY ./models ./models
COPY ./requirements.txt .
COPY *.sh .
COPY *.txt .
COPY *.py .

RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt && \
    pip3 install -U yt-dlp

# Link cuBLAS and cuDNN
RUN export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`

CMD ["/bin/bash"]
